In [4]:
import numpy as np
import pandas as pd

In [5]:
grades = {
    "Atil": 50,
    "Ayse": 60,
    "Atlas": 30
}

In [6]:
s1=pd.Series(grades)
s1

Atil     50
Ayse     60
Atlas    30
dtype: int64

In [8]:
result1=pd.Series([10,5,100], index=["Atil" , "Ayse" , "Atlas"])
result2=pd.Series([120,50,10], index=["Atil" , "Ayse" , "Atlas"])

In [9]:
result1

Atil      10
Ayse       5
Atlas    100
dtype: int64

In [10]:
final_result=result1+result2
final_result

Atil     130
Ayse      55
Atlas    110
dtype: int64

In [12]:
diff1=pd.Series([20,30,40,50], index=['A','B','C','D'])
diff2=pd.Series([10,5,3,1], index=['A','C','F','G'])

In [13]:
diff_sum=diff1+diff2
diff_sum

A    30.0
B     NaN
C    45.0
D     NaN
F     NaN
G     NaN
dtype: float64

In [14]:
data = np.random.rand(4,3)
data

array([[0.53769619, 0.86132889, 0.75600876],
       [0.01374897, 0.50439314, 0.98443404],
       [0.89809344, 0.71063516, 0.74694171],
       [0.08333335, 0.48105024, 0.94786555]])

In [15]:
pd.Series(data)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 3) instead

In [16]:
df=pd.DataFrame(data)
df

          0         1         2
0  0.537696  0.861329  0.756009
1  0.013749  0.504393  0.984434
2  0.898093  0.710635  0.746942
3  0.083333  0.481050  0.947866

In [17]:
type(df)

pandas.core.frame.DataFrame

In [19]:
col0 = df[0]
col0,type(col0)

(0    0.537696
 1    0.013749
 2    0.898093
 3    0.083333
 Name: 0, dtype: float64,
 pandas.core.series.Series)

In [23]:
df= pd.DataFrame(
    data,
    index=["Zeynep", "Atil" , "Mehmet", "Atlas"],
    columns=["maas", "yas", "kıdem"]
)
df

            maas       yas     kıdem
Zeynep  0.537696  0.861329  0.756009
Atil    0.013749  0.504393  0.984434
Mehmet  0.898093  0.710635  0.746942
Atlas   0.083333  0.481050  0.947866

In [27]:
df[["yas","maas"]]

             yas      maas
Zeynep  0.861329  0.537696
Atil    0.504393  0.013749
Mehmet  0.710635  0.898093
Atlas   0.481050  0.083333

In [26]:
df.loc["Atil"]

maas     0.013749
yas      0.504393
kıdem    0.984434
Name: Atil, dtype: float64

In [28]:
df.iloc[:1]

            maas       yas     kıdem
Zeynep  0.537696  0.861329  0.756009

In [30]:
df["extra"]=10
new_df=df
new_df

            maas       yas     kıdem  extra
Zeynep  0.537696  0.861329  0.756009     10
Atil    0.013749  0.504393  0.984434     10
Mehmet  0.898093  0.710635  0.746942     10
Atlas   0.083333  0.481050  0.947866     10

In [31]:
new_df.drop("extra", axis=1)

            maas       yas     kıdem
Zeynep  0.537696  0.861329  0.756009
Atil    0.013749  0.504393  0.984434
Mehmet  0.898093  0.710635  0.746942
Atlas   0.083333  0.481050  0.947866

In [ ]:
new_df2.drop("extra", axis=1)

In [32]:
new_df

            maas       yas     kıdem  extra
Zeynep  0.537696  0.861329  0.756009     10
Atil    0.013749  0.504393  0.984434     10
Mehmet  0.898093  0.710635  0.746942     10
Atlas   0.083333  0.481050  0.947866     10

In [34]:
new_df.drop("extra" , axis=1 , inplace=True )
new_df

            maas       yas     kıdem
Zeynep  0.537696  0.861329  0.756009
Atil    0.013749  0.504393  0.984434
Mehmet  0.898093  0.710635  0.746942
Atlas   0.083333  0.481050  0.947866

In [37]:
new_df_3=new_df.drop("Mehmet")
new_df_3

            maas       yas     kıdem
Zeynep  0.537696  0.861329  0.756009
Atil    0.013749  0.504393  0.984434
Atlas   0.083333  0.481050  0.947866

In [38]:
new_df.loc["Atlas", "maas"]=100
new_df

              maas       yas     kıdem
Zeynep    0.537696  0.861329  0.756009
Atil      0.013749  0.504393  0.984434
Mehmet    0.898093  0.710635  0.746942
Atlas   100.000000  0.481050  0.947866

In [40]:
new_df.iloc[2,0]=100
new_df

              maas       yas     kıdem
Zeynep    0.537696  0.861329  0.756009
Atil      0.013749  0.504393  0.984434
Mehmet  100.000000  0.710635  0.746942
Atlas   100.000000  0.481050  0.947866

In [41]:
new_df>0

        maas   yas  kıdem
Zeynep  True  True   True
Atil    True  True   True
Mehmet  True  True   True
Atlas   True  True   True

In [43]:
new_df[new_df>1]

         maas  yas  kıdem
Zeynep    NaN  NaN    NaN
Atil      NaN  NaN    NaN
Mehmet  100.0  NaN    NaN
Atlas   100.0  NaN    NaN

In [45]:
new_df[new_df["maas"]>1]

         maas       yas     kıdem
Mehmet  100.0  0.710635  0.746942
Atlas   100.0  0.481050  0.947866

In [46]:
new_df[new_df["yas"]>0.3]

              maas       yas     kıdem
Zeynep    0.537696  0.861329  0.756009
Atil      0.013749  0.504393  0.984434
Mehmet  100.000000  0.710635  0.746942
Atlas   100.000000  0.481050  0.947866

In [47]:
rf=df.reset_index()
rf

    index        maas       yas     kıdem
0  Zeynep    0.537696  0.861329  0.756009
1    Atil    0.013749  0.504393  0.984434
2  Mehmet  100.000000  0.710635  0.746942
3   Atlas  100.000000  0.481050  0.947866

In [48]:
rf.loc[0]

index      Zeynep
maas     0.537696
yas      0.861329
kıdem    0.756009
Name: 0, dtype: object

In [49]:
df.reset_index(drop=True)

         maas       yas     kıdem
0    0.537696  0.861329  0.756009
1    0.013749  0.504393  0.984434
2  100.000000  0.710635  0.746942
3  100.000000  0.481050  0.947866

In [52]:
ni=["zy","at","mh","al"]
df["ni"]=ni
df

              maas       yas     kıdem  ni
Zeynep    0.537696  0.861329  0.756009  zy
Atil      0.013749  0.504393  0.984434  at
Mehmet  100.000000  0.710635  0.746942  mh
Atlas   100.000000  0.481050  0.947866  al

In [53]:
df.set_index("ni",inplace=True)
df

          maas       yas     kıdem
ni
zy    0.537696  0.861329  0.756009
at    0.013749  0.504393  0.984434
mh  100.000000  0.710635  0.746942
al  100.000000  0.481050  0.947866

In [54]:
df.loc["at"]

maas     0.013749
yas      0.504393
kıdem    0.984434
Name: at, dtype: float64

In [57]:
w=pd.read_excel("/content/sample_data/6-weather.xlsx")
w

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [59]:
w_tail()

NameError: name 'w_tail' is not defined

In [60]:
w.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   9 non-null      int64
 1   New York   9 non-null      int64
 2   Amsterdam  9 non-null      int64
 3   Paris      9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

In [61]:
w.describe()

        Istanbul   New York  Amsterdam      Paris
count   9.000000   9.000000   9.000000   9.000000
mean   21.444444  13.111111  16.777778  15.555556
std     3.609401   2.147350   2.538591   2.351123
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  12.000000  15.000000  14.000000
50%    21.000000  13.000000  16.000000  15.000000
75%    22.000000  15.000000  18.000000  16.000000
max    28.000000  16.000000  22.000000  20.000000

In [62]:
w.count()

Istanbul     9
New York     9
Amsterdam    9
Paris        9
dtype: int64

In [66]:
w.shape()

TypeError: 'tuple' object is not callable

In [69]:
w.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False      False  False
2     False     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False     False      False  False
6     False     False      False  False
7     False     False      False  False
8     False     False      False  False

In [70]:
w.isna().sum()

Istanbul     0
New York     0
Amsterdam    0
Paris        0
dtype: int64